"""
Django settings for cms project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import configparser
import os
import sys

from django.core.management.color import color_style
from pathlib import Path
style = color_style()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

APP_NAME = 'cms'

ETC_DIR = '/etc/cms'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

KEY_PATH = os.path.join(ETC_DIR, 'crypto_fields')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5((#k_fhd-6-a(aocadjq3)t%v_kmwx!f@#a7tc_o0e$pzs%ts'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
LIVE_SYSTEM = None

ALLOWED_HOSTS = ['127.0.0.1','10.113.200.54']

INDEX_PAGE = 'cms.bhp.org.bw'

APP_NAME = 'cms'

LOGIN_REDIRECT_URL = 'home_url'

SITE_ID = 40
REVIEWER_SITE_ID = 1

CONFIG_FILE = f'{APP_NAME}.ini'
CONFIG_PATH = os.path.join(ETC_DIR, CONFIG_FILE)

sys.stdout.write(style.SUCCESS(f'  * Reading config from {CONFIG_FILE}\n'))
config = configparser.ConfigParser()
config.read(CONFIG_PATH)

# email configurations
EMAIL_BACKEND = config['email_conf'].get('email_backend')
EMAIL_HOST = config['email_conf'].get('email_host')
EMAIL_USE_TLS = config['email_conf'].get('email_use_tls')
EMAIL_PORT = config['email_conf'].get('email_port')
EMAIL_HOST_USER = config['email_conf'].get('email_user')
EMAIL_HOST_PASSWORD = config['email_conf'].get('email_host_pwd')

# sms configuration
BASE_API_URL = config['edc_sms']['base_api_url']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'django_q',
    'django_crypto_fields.apps.AppConfig',
    'edc_dashboard.apps.AppConfig',
    'edc_device.apps.AppConfig',
    'edc_identifier.apps.AppConfig',
    'edc_model_admin.apps.AppConfig',
    'edc_navbar.apps.AppConfig',
    'cms_dashboard.apps.AppConfig',
    'cms.apps.EdcBaseAppConfig',
    'cms.apps.EdcSmsAppConfig',
    'contract.apps.AppConfig',
    'cms.apps.AppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'edc_dashboard.middleware.DashboardMiddleware',
    'edc_subject_dashboard.middleware.DashboardMiddleware',
]

ROOT_URLCONF = 'cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

mysql_config = configparser.ConfigParser()
mysql_config.read(os.path.join(ETC_DIR, 'mysql.ini'))

HOST = mysql_config['mysql']['host']
DB_USER = mysql_config['mysql']['user']
DB_PASSWORD = mysql_config['mysql']['password']
DB_NAME = mysql_config['mysql']['database']
PORT = mysql_config['mysql']['port']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': HOST,   # Or an IP Address that your DB is hosted on
        'PORT': PORT,
    }
}

# Django q configurations

Q_CLUSTER = {
    'name': 'cms',
    'retry': 60,
    'orm': 'default',
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Gaborone'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# dashboards
DASHBOARD_URL_NAMES = {
    'appraisal_dashboard_url': 'cms_dashboard:appraisal_dashboard_url',
    'appraisal_listboard_url': 'cms_dashboard:appraisal_listboard_url',
    'employee_dashboard_url': 'cms_dashboard:employee_dashboard_url',
    'employee_listboard_url': 'cms_dashboard:employee_listboard_url',
    'emp_contract_listboard_url': 'cms_dashboard:emp_contract_listboard_url',
    'pi_contract_listboard_url': 'cms_dashboard:pi_contract_listboard_url',
    'pi_listboard_url': 'cms_dashboard:pi_listboard_url',
    'pi_dashboard_url': 'cms_dashboard:pi_dashboard_url',
    'consultant_contract_listboard_url': 'cms_dashboard:'
                                         'consultant_contract_listboard_url',
    'consultant_listboard_url': 'cms_dashboard:consultant_listboard_url',
    'consultant_dashboard_url': 'cms_dashboard:consultant_dashboard_url',
    'contract_listboard_url': 'cms_dashboard:contract_listboard_url',
    'contact_listboard_url': 'edc_sms:contact_listboard_url',
}

DASHBOARD_BASE_TEMPLATES = {
    'listboard_base_template': 'cms/base.html',
    'appraisal_dashboard_template': 'cms_dashboard/employee/appraisal_dashboard.html',
    'appraisal_listboard_template': 'cms_dashboard/employee/appraisal_listboard.html',
    'contract_listboard_template': 'cms_dashboard/contract/contract_listboard.html',
    'allcontracts_listboard_template': 'cms_dashboard/contract/'
                                       'allcontracts_listboard.html',
    'dashboard_base_template': 'cms/base.html',
    'employee_dashboard_template': 'cms_dashboard/employee/employee_dashboard.html',
    'employee_listboard_template': 'cms_dashboard/employee/employee_listboard.html',
    'pi_dashboard_template': 'cms_dashboard/pi/pi_dashboard.html',
    'pi_listboard_template': 'cms_dashboard/pi/pi_listboard.html',
    'consultant_listboard_template': 'cms_dashboard/consultant/consultant_listboard.html',
    'consultant_dashboard_template': 'cms_dashboard/consultant/consultant_dashboard.html',
}
